export const usersOrders = [
    {
        id: 1,
        name: "Tony Reichert",
        amount: "1000",
        status: "انجام شده",
        date: "1403/01/22",
        email: "tony.reichert@example.com",
    },
    {
        id: 2,
        name: "Zoey Lang",
        amount: "1000",
        status: "کنسل شده",
        date: "1403/01/22",
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        name: "Jane Fisher",
        amount: "1000",
        status: "انجام شده",
        date: "1403/01/22",
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        name: "William Howard",
        amount: "1000",
        status: "درحال انتظار",
        date: "1403/01/22",
        email: "william.howard@example.com",
    },
    {
        id: 5,
        name: "علی محمدی",
        amount: "1000",
        status: "کنسل شده",
        date: "1403/01/22",
        email: "kristen.cooper@example.com",
    },
    {
        id: 6,
        name: "Michael Smith",
        amount: "1200",
        status: "انجام شده",
        date: "1403/01/22",
        email: "michael.smith@example.com",
    },
    {
        id: 7,
        name: "Emily Johnson",
        amount: "1500",
        status: "درحال انتظار",
        date: "1403/01/22",
        email: "emily.johnson@example.com",
    },
    {
        id: 8,
        name: "David Brown",
        amount: "800",
        status: "کنسل شده",
        date: "1403/01/22",
        email: "david.brown@example.com",
    },
    {
        id: 9,
        name: "Sophia Davis",
        amount: "900",
        status: "انجام شده",
        date: "1403/01/22",
        email: "sophia.davis@example.com",
    },
    {
        id: 10,
        name: "James Wilson",
        amount: "1100",
        status: "درحال انتظار",
        date: "1403/01/22",
        email: "james.wilson@example.com",
    },
    {
        id: 11,
        name: "Isabella Martinez",
        amount: "1300",
        status: "کنسل شده",
        date: "1403/01/22",
        email: "isabella.martinez@example.com",
    },
];
export const usersOrdersINITIAL_VISIBLE_COLUMNS = [
    "id",
    "name",
    "status",
    "date",
    "amount",
    "actions",
];
export const products = [
    {
        id: 1,
        name: "Tony Reichert",
        amount: "1000",
        status: "تکمیل شده",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 2,
        name: "Zoey Lang",
        amount: "1000",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 3,
        name: "Jane Fisher",
        amount: "1000",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 4,
        name: "William Howard",
        amount: "1000",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 5,
        name: "علی محمدی",
        amount: "1000",
        status: "تکمیل شده",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 6,
        name: "Michael Smith",
        amount: "1200",
        status: "تکمیل شده",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 7,
        name: "Emily Johnson",
        amount: "1500",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 8,
        name: "David Brown",
        amount: "800",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 9,
        name: "Sophia Davis",
        amount: "900",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 10,
        name: "James Wilson",
        amount: "1100",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 11,
        name: "Isabella Martinez",
        amount: "1300",
        status: "ناقص",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
];
export const productsINITIAL_VISIBLE_COLUMNS = [
    "id",
    "name",
    "status",
    "date",
    "amount",
    "actions",
];
export const users = [
    {
        id: 1,
        name: "Tony Reichert",
        amount: "1000",
        role: "ادمین",
        date: "1403/01/22",
        email: "tony.reichert@example.com",
    },
    {
        id: 2,
        name: "Zoey Lang",
        amount: "1000",
        role: "کاربر",
        date: "1403/01/22",
        email: "zoey.lang@example.com",
    },
    {
        id: 3,
        name: "Jane Fisher",
        amount: "1000",
        role: "کاربر",
        date: "1403/01/22",
        email: "jane.fisher@example.com",
    },
    {
        id: 4,
        name: "William Howard",
        amount: "1000",
        role: "کاربر",
        date: "1403/01/22",
        email: "william.howard@example.com",
    },
    {
        id: 5,
        name: "علی محمدی",
        amount: "1000",
        role: "کاربر",
        date: "1403/01/22",
        email: "kristen.cooper@example.com",
    },
    {
        id: 6,
        name: "Michael Smith",
        amount: "1200",
        role: "کاربر",
        date: "1403/01/22",
        email: "michael.smith@example.com",
    },
    {
        id: 7,
        name: "Emily Johnson",
        amount: "1500",
        role: "کاربر",
        date: "1403/01/22",
        email: "emily.johnson@example.com",
    },
    {
        id: 8,
        name: "David Brown",
        amount: "800",
        role: "کاربر",
        date: "1403/01/22",
        email: "david.brown@example.com",
    },
    {
        id: 9,
        name: "Sophia Davis",
        amount: "900",
        role: "کاربر",
        date: "1403/01/22",
        email: "sophia.davis@example.com",
    },
    {
        id: 10,
        name: "James Wilson",
        amount: "1100",
        role: "کاربر",
        date: "1403/01/22",
        email: "james.wilson@example.com",
    },
    {
        id: 11,
        name: "Isabella Martinez",
        amount: "1300",
        role: "کاربر",
        date: "1403/01/22",
        email: "isabella.martinez@example.com",
    },
];
export const usersINITIAL_VISIBLE_COLUMNS = [
    "id",
    "name",
    "role",
    "date",
    "actions",
];
export const blogs = [
    {
        id: 1,
        title: "Understanding React",
        category: "Web Development",
        author: "Tony Reichert",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 2,
        title: "Advanced JavaScript",
        category: "Programming",
        author: "Zoey Lang",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 3,
        title: "UI/UX Design Principles",
        category: "Design",
        author: "Jane Fisher",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 4,
        title: "Node.js for Beginners",
        category: "Backend Development",
        author: "William Howard",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 5,
        title: "Introduction to AI",
        category: "Artificial Intelligence",
        author: "علی محمدی",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 6,
        title: "Data Structures in Python",
        category: "Programming",
        author: "Michael Smith",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 7,
        title: "Cloud Computing Basics",
        category: "Cloud Computing",
        author: "Emily Johnson",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 8,
        title: "Cybersecurity Essentials",
        category: "Security",
        author: "David Brown",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 9,
        title: "Machine Learning 101",
        category: "Machine Learning",
        author: "Sophia Davis",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
    {
        id: 10,
        title: "Blockchain Explained",
        category: "Blockchain",
        author: "James Wilson",
        date: "1403/01/22",
        image: "/images/blog1-img2.png",
    },
    {
        id: 11,
        title: "Digital Marketing Trends",
        category: "Marketing",
        author: "Isabella Martinez",
        date: "1403/01/22",
        image: "/images/blog1-img1.png",
    },
];

export const blogsINITIAL_VISIBLE_COLUMNS = [
    "id",
    "title",
    "category",
    "author",
    "date",
    "actions",
];

export const columns = [
    { name: "#", uid: "id", sortable: true },
    { name: "نام", uid: "name", sortable: true },
    { name: "نقش", uid: "role", sortable: true },
    { name: "ایمیل", uid: "email" },
    { name: "وضعیت", uid: "status", sortable: true },
    { name: "تاریخ", uid: "date", sortable: true },
    { name: "قیمت", uid: "amount", sortable: true },
    { name: "عملیات", uid: "actions" },
];

export const blogColumns = [
    { name: "#", uid: "id", sortable: true },
    { name: "عنوان", uid: "title", sortable: true },
    { name: "دسته بندی", uid: "category", sortable: true },
    { name: "نویسنده", uid: "author" },
    { name: "تاریخ ایجاد ", uid: "date", sortable: true },
    { name: "عملیات", uid: "actions" },
];

export const statusOptions = [
    { name: "انجام شده", uid: "انجام شده" },
    { name: "درحال انتظار", uid: "درحال انتظار" },
    { name: "کنسل شده", uid: "کنسل شده" },
];

export const rolesOptions = [
    { name: "ادمین", uid: "ادمین" },
    { name: "کاربر", uid: "کاربر" },
];

export const productProgresOptions = [
    { name: "تکمیل شده", uid: "تکمیل شده" },
    { name: "ناقص", uid: "ناقص" },
];

export const statusColorMap = {
    "انجام شده": "success",
    "درحال انتظار": "warning",
    "کنسل شده": "danger",
    "ادمین": "secondary",
    "کاربر": "primary",
    "تکمیل شده": "success",
    "ناقص": "warning",
}; 